using System;
using System.ComponentModel;
using System.Runtime.InteropServices;

using Microsoft.VisualStudio.Shell;

namespace Tasler.RenewedPowerCommands.OptionPages
{
	public enum DisabledEnabled
	{
		Disabled,
		Enabled,
	}

	[ComVisible(true)]
	[ClassInterface(ClassInterfaceType.AutoDual)]
	[Guid("7FF0673B-4E19-45FD-86E3-09473884C44F")]
	public class OptionsPage : DialogPage
	{
		[Category("Save behavior")]
		[DefaultValue(false)]
		[DisplayName("Format document on save")]
		[Description("Enables formatting of tabs, spaces and other characters in a document to be saved. It is equivalent to using Format Document command under the Edit->Advanced menu. Disabled by default.")]
		public bool FormatOnSave { get; set; }

		[Category("Save behavior")]
		[DefaultValue(false)]
		[DisplayName("Remove and Sort Usings on save")]
		[Description("Removes unused using statements and sorts the remaining using statements in the C# document being saved. Disabled by default.")]
		public bool RemoveAndSortUsingsOnSave { get; set; }

		[Category("Commands")]
		[DefaultValue(0)]
		[DisplayName("Collapse Projects")]
		[Description("Collapses a project or projects in the Solution Explorer starting from the root selected node. This option resides in three different places on the Solution Explorer: Solution, Solution folders and Project nodes respectively.")]
		public DisabledEnabled CollapseProjectsCommand { get; set; }

		[Category("Commands")]
		[DefaultValue(0)]
		[DisplayName("Remove and Sort Usings")]
		[Description("Removes and sort using statements for all classes given a project. It is useful, for example, in removing or organizing the using statements generated by a wizard. This command can be executed from a solution node or a single project node.")]
		public DisabledEnabled RemoveAndSortUsingsCommand { get; set; }
	}
}
