//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasler.RenewedPowerCommands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tasler.RenewedPowerCommands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerCommands Renewed.
        /// </summary>
        internal static string _15600 {
            get {
                return ResourceManager.GetString("15600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of power commands for Visual Studio.
        /// </summary>
        internal static string _25288 {
            get {
                return ResourceManager.GetString("25288", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewed PowerCommands Options (description).
        /// </summary>
        internal static string _2891 {
            get {
                return ResourceManager.GetString("2891", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string _41182 {
            get {
                return ResourceManager.GetString("41182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string _4606 {
            get {
                return ResourceManager.GetString("4606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerCommands for Visual Studio.
        /// </summary>
        internal static string _9394 {
            get {
                return ResourceManager.GetString("9394", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Projects; Remove and Sort Usings.
        /// </summary>
        internal static string ToolsOptionsKeywords_Commands {
            get {
                return ResourceManager.GetString("ToolsOptionsKeywords_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove and Sort Usings on save.
        /// </summary>
        internal static string ToolsOptionsKeywords_General {
            get {
                return ResourceManager.GetString("ToolsOptionsKeywords_General", resourceCulture);
            }
        }
    }
}
